name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install
      run: |
       sudo apt-get update
       wget https://github.com/radareorg/radare2/releases/download/5.8.8/radare2_5.8.8_amd64.deb
       sudo dpkg -i radare2_5.8.8_amd64.deb
       sudo apt install default-jre apksigner zipalign
       pip3 install -r requirements.txt      
      
      
    - name: Run
      run: python3 patch_apk.py

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
          name: app_patched
          path: "app_patched.apk"
